# Generated by Django 4.0.5 on 2022-06-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
